
version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/be
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root

hooks:
  AfterInstall:
    - location: scripts/build.sh
      timeout: 6000
      runas: root
